### ISSUE TITLE
Addition of Low Level Design of Snake and Ladder Game

### ISSUE THREAD

**Issue by Soumya1219** [usmanbvp/DSAProblemsHub#22]
I want to add low level design of Snake and Ladder Game because low level design is very important concept in DSA for advanced programmers and many interviews includes low level design problems so this will be a good start. 

Kindly assign me with this issue. I would like to contribute. :)

**Comment by Soumya1219** [comment]
Why is it closed?

**Comment by usmanbvp** [comment]
Ok @Soumya1219
